export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  NOTIFICATIONS: "/notifications",
  STUDENT: {
    ROOT: "/student",
    DASHBOARD: "/student/dashboard",
    REQUESTS: "/student/requests",
    REQUEST_DETAILS: "/student/requests/:id",
    REQUEST_CREATE: "/student/requests/create",
    INSTANT_REQUESTS: "/student/instant-requests",
    INSTANT_REQUEST_CREATE: "/student/instant-requests/create",
    INSTANT_REQUEST_DETAILS: "/student/instant-requests/:id",
    GROUP_REQUESTS: "/student/group-requests",
    GROUP_REQUEST_CREATE: "/student/group-requests/create",
    GROUP_REQUEST_DETAILS: "/student/group-requests/:id",
    INSTRUCTORS: "/student/instructors",
    INSTRUCTOR_DETAILS: "/student/instructors/:instructorId",
    CHAT: "/student/chat",
    SESSIONS: "/student/sessions",
    SESSION_DETAILS: "/student/sessions/:sessionId",
    PAYMENTS: "/student/payments",
    PAYMENT_CONFIRMATION: "/student/payments/session/:sessionId",
    REVIEWS: "/student/reviews",
    PROFILE: "/student/profile",
    SETTINGS: "/student/settings",
  },
  INSTRUCTOR: {
    ROOT: "/instructor",
    DASHBOARD: "/instructor/dashboard",
    REQUESTS: "/instructor/requests",
    REQUEST_DETAILS: "/instructor/requests/:requestId",
    INSTANT_REQUESTS: "/instructor/instant-requests",
    INSTANT_REQUEST_DETAILS: "/instructor/instant-requests/:id",
    SESSIONS: "/instructor/sessions",
    SESSION_DETAILS: "/instructor/sessions/:sessionId",
    CHAT: "/instructor/chat",
    WALLET: "/instructor/wallet",
    REVIEWS: "/instructor/reviews",
    PROFILE: "/instructor/profile",
    AVAILABILITY: "/instructor/availability",
    SETTINGS: "/instructor/settings",
  },
  ADMIN: {
    ROOT: "/admin",
    DASHBOARD: "/admin/dashboard",
    USERS: "/admin/users",
    REQUESTS: "/admin/requests",
    SESSIONS: "/admin/sessions",
    PAYMENTS: "/admin/payments",
    REVIEWS: "/admin/reviews",
  },
} as const;
